// Code generated by mockery v1.0.0. DO NOT EDIT.

package smtpmocks

import mock "github.com/stretchr/testify/mock"
import smtputil "github.com/hectane/hectane/internal/smtputil"

// Connecter is an autogenerated mock type for the Connecter type
type Connecter struct {
	mock.Mock
}

// SMTPConnect provides a mock function with given fields: hostname
func (_m *Connecter) SMTPConnect(hostname string) (smtputil.Client, error) {
	ret := _m.Called(hostname)

	var r0 smtputil.Client
	if rf, ok := ret.Get(0).(func(string) smtputil.Client); ok {
		r0 = rf(hostname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(smtputil.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hostname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
