// Code generated by mockery v1.0.0. DO NOT EDIT.

package queuemocks

import mock "github.com/stretchr/testify/mock"

// MailServerFinder is an autogenerated mock type for the MailServerFinder type
type MailServerFinder struct {
	mock.Mock
}

// FindServers provides a mock function with given fields: host
func (_m *MailServerFinder) FindServers(host string) ([]string, error) {
	ret := _m.Called(host)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
